### ISSUE TITLE
Python Extension Not Supported

### ISSUE THREAD

**Issue by shakeelsamsu** [MiniDomo/Kattis#1]
The Kattis Table Generator v1.0.1 lacks support for Python Files. The attached screenshot is an example of the problem experienced with the current release.
![image](https://user-images.githubusercontent.com/16440459/50568539-0d4cef00-0d19-11e9-92cc-08c5acb43319.png)
Proposed Fix: Change to Extensions.cs

**Comment by minidomo** [comment]
Fixed
